version: '3.9'

services:
  metabot:
    build:
      context: .
    container_name: metabot
    env_file:
      - /root/.env
    environment:
      - DOTNET_ENVIRONMENT=Production
    restart: unless-stopped
